# Finland GTFS schema keeps stoptimesWithoutPatterns on Stop.
query StopDeparturesQuery($id: String!) {
  stop(id: $id) {
    name
    code
    zoneId
    vehicleMode
    direction
    patterns {
      name
      headsign
      directionId
      route {
        shortName
        longName
        mode
      }
    }
    stoptimesWithoutPatterns {
      scheduledDeparture
      realtimeDeparture
      realtime
      realtimeState
      serviceDay
      headsign
      trip {
        route {
          shortName
        }
      }
    }
  }
}
